{% set version = "1.28.0" %}

package:
  name: ecmwf_grib
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: d4355cbec907dd0ef6e734c8d6f938540aad2d6449187c03cdc2fb7395087261

build:
  number: 1001
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - jasper
    - libpng
    - libnetcdf
    - hdf5
  run:
    - jasper
    - libpng
    - libnetcdf
    - hdf5

test:
  commands:
    - grib_info
    - ls $(grib_info -t)
    - ls $(grib_info -d)
    - test -f ${PREFIX}/lib/libgrib_api.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f77.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f90.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f77.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f90.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache 2.0
  license_file: LICENSE
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
    - pelson
    - rhattersley
    - kynan
