{% set version = "1.19.0" %}

package:
  name: ecmwf_grib
  version: {{ version }}

source:
  fn: grib_api-{{ version }}.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: caec66c2d54331de9830dde853195262a1859bab36d5d03b4d44ac55784d921d

build:
  number: 1
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - cmake
    - jasper  # [not win]
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - gcc  # [not win]
    - msinttypes  # [win and py<35]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - jasper  # [not win]
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - grib_info
    - ls $(grib_info -t)  # [not win]
    - ls $(grib_info -d)  # [not win]
    - test -f ${PREFIX}/lib/libgrib_api.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f77.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f90.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f77.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f90.dylib  # [osx]
    - conda inspect linkages -p $PREFIX ecmwf_grib  # [not win]
    - conda inspect objects -p $PREFIX ecmwf_grib  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache-2.0
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
    - pelson
    - rhattersley
    - kynan
