travis:
  secure:
    BINSTAR_TOKEN: VHM46cJ/l54l3e7Dgq6ae/pc7cxUELmLu8eXProL5rjLn09CTqLDS0nOGxVt6GWMXAWkM1Dga+uwLbegfNL5UpY6BF43yVGXrtviJ7UUfJESpCABo92/DijX4nmgotTHsPnsjVF/P0icu0Slnm5q/AX0d1CDuowd3H0/z6E4gy7Faz+VvHhiHreNodUXQ7bJ4BhSnB5iPbRZ0Jfh7kVjLx6OMdkMSh4yuy+Rvufj+AV3t9DAjemGC5nXgwrz4WHoAglZFAo8sbBCmWggX8o9yRNORDIEhpYVsEfWspxfWrQavIcl5vxrHBh8POCoXtspvmH9cdpfEwQjgM/emgK78ZSvHvpSpzvno9+h+7tw36yKxRamOECAYlUSpxTUeyCdTGJDNnIOTQJlfJBASfxbNjp+aEm03EQsN6+EI/gpVsue3KccrGlxuZwregjmDcJeoBRRCW6tYYn5oyJ0o6yFnzn8Wt4ghJ/ujv2zORdt/XSw2ijpKRT7//9JgRIbfZ6OkVWPHckJOeeioZDX+7fCvg6BEnmWdOwvzKJ3bzcnOj7tf4va/J5CrGp5iLEdmIHwCCNsFpmopcpsND+pMw07k19as4U1Dz+kasl1QU+xmkWwAts9eLakj3sTJ/6PawNEKFCMXJwtePjqSf6/0JEVfQEuQYE/7/ISfn97fbyk5Oc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
